import type { CloudPreset } from "./types.js";

export const CLOUD_PRESETS: CloudPreset[] = [
  // --- v0.1.0 original 7 presets (unchanged) ---
  {
    id: "fair-weather-cumulus",
    name: "Fair Weather Cumulus",
    description: "Scattered puffy cumulus clouds on a clear day, flat bases and rounded tops",
    tags: ["cumulus", "fair", "puffy", "scattered"],
    category: "clouds",
    cloudType: "cumulus",
    algorithm: "discrete",
    coverage: 0.3,
    altitude: 0.15,
    scale: 1.0,
    cloudCount: 5,
    edgeComplexity: 0.6,
    turbulence: 0.3,
    cloudColor: "#FFFFFF",
    shadowColor: "#B0B8C8",
    highlightColor: "#FFFFFF",
    opacity: 0.9,
    sunAngle: 135,
    sunElevation: 0.6,
  },
  {
    id: "towering-cumulus",
    name: "Towering Cumulus",
    description: "Large vertical cumulus with dramatic light and shadow",
    tags: ["cumulus", "towering", "dramatic", "large"],
    category: "clouds",
    cloudType: "cumulus",
    algorithm: "discrete",
    coverage: 0.4,
    altitude: 0.1,
    scale: 1.5,
    cloudCount: 3,
    edgeComplexity: 0.8,
    turbulence: 0.5,
    cloudColor: "#F8F8FF",
    shadowColor: "#8090A8",
    highlightColor: "#FFFFFF",
    opacity: 0.95,
    sunAngle: 150,
    sunElevation: 0.5,
  },
  {
    id: "overcast-stratus",
    name: "Overcast Stratus",
    description: "Flat uniform cloud layer covering most of the sky",
    tags: ["stratus", "overcast", "flat", "gray"],
    category: "clouds",
    cloudType: "stratus",
    algorithm: "threshold",
    coverage: 0.85,
    altitude: 0.2,
    scale: 1.0,
    cloudCount: 1,
    edgeComplexity: 0.2,
    turbulence: 0.15,
    cloudColor: "#D0D4DC",
    shadowColor: "#A8B0BC",
    highlightColor: "#E0E4EC",
    opacity: 0.85,
    sunAngle: 135,
    sunElevation: 0.4,
  },
  {
    id: "stratocumulus-field",
    name: "Stratocumulus Field",
    description: "Regular field of rounded cloud patches with gaps",
    tags: ["stratocumulus", "field", "regular", "patchy"],
    category: "clouds",
    cloudType: "stratocumulus",
    algorithm: "threshold",
    coverage: 0.6,
    altitude: 0.18,
    scale: 0.8,
    cloudCount: 1,
    edgeComplexity: 0.5,
    turbulence: 0.35,
    cloudColor: "#E8ECF0",
    shadowColor: "#A0A8B8",
    highlightColor: "#F8F8FF",
    opacity: 0.9,
    sunAngle: 120,
    sunElevation: 0.55,
  },
  {
    id: "wispy-cirrus",
    name: "Wispy Cirrus",
    description: "High-altitude ice crystal streaks, thin and translucent",
    tags: ["cirrus", "wispy", "high", "thin"],
    category: "clouds",
    cloudType: "cirrus",
    algorithm: "streak",
    coverage: 0.2,
    altitude: 0.05,
    scale: 1.2,
    cloudCount: 8,
    edgeComplexity: 0.3,
    turbulence: 0.2,
    cloudColor: "#F0F4FF",
    shadowColor: "#D0D8E8",
    highlightColor: "#FFFFFF",
    opacity: 0.4,
    sunAngle: 135,
    sunElevation: 0.7,
  },
  {
    id: "sunset-cumulus",
    name: "Sunset Cumulus",
    description: "Cumulus clouds lit from below by warm sunset light",
    tags: ["sunset", "warm", "golden", "dramatic"],
    category: "clouds",
    cloudType: "cumulus",
    algorithm: "discrete",
    coverage: 0.35,
    altitude: 0.12,
    scale: 1.0,
    cloudCount: 4,
    edgeComplexity: 0.7,
    turbulence: 0.4,
    cloudColor: "#F8E8D8",
    shadowColor: "#7868A0",
    highlightColor: "#FFD8A0",
    opacity: 0.9,
    sunAngle: 180,
    sunElevation: 0.15,
  },
  {
    id: "storm-clouds",
    name: "Storm Clouds",
    description: "Dark heavy cumulonimbus with dramatic light contrast",
    tags: ["storm", "dark", "dramatic", "cumulonimbus"],
    category: "clouds",
    cloudType: "cumulonimbus",
    algorithm: "discrete",
    coverage: 0.7,
    altitude: 0.05,
    scale: 2.0,
    cloudCount: 2,
    edgeComplexity: 0.9,
    turbulence: 0.7,
    cloudColor: "#90A0B0",
    shadowColor: "#404858",
    highlightColor: "#C8D0DC",
    opacity: 0.95,
    sunAngle: 160,
    sunElevation: 0.3,
  },

  // --- v0.2.0 new presets (15 new cloud types) ---
  {
    id: "mackerel-sky",
    name: "Mackerel Sky",
    description: "High-altitude cirrocumulus in a regular rippled pattern like fish scales",
    tags: ["cirrocumulus", "mackerel", "high", "cellular", "pattern"],
    category: "clouds",
    cloudType: "cirrocumulus",
    algorithm: "threshold",
    coverage: 0.5,
    altitude: 0.05,
    scale: 0.7,
    cloudCount: 1,
    edgeComplexity: 0.3,
    turbulence: 0.2,
    cloudColor: "#F0F4FF",
    shadowColor: "#C8D0E0",
    highlightColor: "#FFFFFF",
    opacity: 0.5,
    sunAngle: 135,
    sunElevation: 0.7,
  },
  {
    id: "cirrostratus-veil",
    name: "Cirrostratus Veil",
    description: "Thin uniform high-altitude ice crystal veil creating a milky sky",
    tags: ["cirrostratus", "veil", "thin", "high", "uniform"],
    category: "clouds",
    cloudType: "cirrostratus",
    algorithm: "threshold",
    coverage: 0.7,
    altitude: 0.05,
    scale: 1.0,
    cloudCount: 1,
    edgeComplexity: 0.15,
    turbulence: 0.1,
    cloudColor: "#F0F0F8",
    shadowColor: "#D8D8E4",
    highlightColor: "#FFFFFF",
    opacity: 0.35,
    sunAngle: 135,
    sunElevation: 0.65,
  },
  {
    id: "altocumulus-field",
    name: "Altocumulus Field",
    description: "Mid-level cloud cells in a patchy field with rounded edges and blue gaps",
    tags: ["altocumulus", "mid", "cells", "patchy"],
    category: "clouds",
    cloudType: "altocumulus",
    algorithm: "threshold",
    coverage: 0.5,
    altitude: 0.1,
    scale: 0.8,
    cloudCount: 1,
    edgeComplexity: 0.4,
    turbulence: 0.3,
    cloudColor: "#E8ECF4",
    shadowColor: "#A0A8B8",
    highlightColor: "#F8FAFF",
    opacity: 0.75,
    sunAngle: 130,
    sunElevation: 0.6,
  },
  {
    id: "altostratus-sheet",
    name: "Altostratus Sheet",
    description: "Uniform mid-level cloud sheet filtering sunlight into a gray-blue sky",
    tags: ["altostratus", "mid", "uniform", "sheet", "gray"],
    category: "clouds",
    cloudType: "altostratus",
    algorithm: "threshold",
    coverage: 0.75,
    altitude: 0.1,
    scale: 1.0,
    cloudCount: 1,
    edgeComplexity: 0.2,
    turbulence: 0.2,
    cloudColor: "#C8D0DC",
    shadowColor: "#98A0B0",
    highlightColor: "#D8E0E8",
    opacity: 0.7,
    sunAngle: 135,
    sunElevation: 0.45,
  },
  {
    id: "castellanus-turrets",
    name: "Castellanus Turrets",
    description: "Small tower-like cumulus rising from a mid-level base, instability indicator",
    tags: ["castellanus", "turrets", "mid", "instability"],
    category: "clouds",
    cloudType: "altocumulus-castellanus",
    algorithm: "discrete",
    coverage: 0.3,
    altitude: 0.1,
    scale: 0.7,
    cloudCount: 6,
    edgeComplexity: 0.6,
    turbulence: 0.4,
    cloudColor: "#E8ECF4",
    shadowColor: "#90A0B0",
    highlightColor: "#F8FAFF",
    opacity: 0.8,
    sunAngle: 140,
    sunElevation: 0.55,
  },
  {
    id: "cumulus-congestus",
    name: "Cumulus Congestus",
    description: "Tall towering cumulus with vigorous vertical development",
    tags: ["cumulus", "congestus", "towering", "tall", "vertical"],
    category: "clouds",
    cloudType: "cumulus-congestus",
    algorithm: "discrete",
    coverage: 0.4,
    altitude: 0.08,
    scale: 1.8,
    cloudCount: 2,
    edgeComplexity: 0.85,
    turbulence: 0.55,
    cloudColor: "#F8F8FF",
    shadowColor: "#7080A0",
    highlightColor: "#FFFFFF",
    opacity: 0.95,
    sunAngle: 145,
    sunElevation: 0.5,
  },
  {
    id: "nimbostratus-overcast",
    name: "Nimbostratus Overcast",
    description: "Dark thick low cloud layer covering the entire sky, continuous rain expected",
    tags: ["nimbostratus", "dark", "thick", "rain", "overcast"],
    category: "clouds",
    cloudType: "nimbostratus",
    algorithm: "threshold",
    coverage: 0.9,
    altitude: 0.15,
    scale: 1.0,
    cloudCount: 1,
    edgeComplexity: 0.25,
    turbulence: 0.2,
    cloudColor: "#8890A0",
    shadowColor: "#606878",
    highlightColor: "#A0A8B4",
    opacity: 0.9,
    sunAngle: 135,
    sunElevation: 0.3,
  },
  {
    id: "cumulonimbus-anvil",
    name: "Cumulonimbus Anvil",
    description: "Massive thunderstorm cloud with flat anvil-shaped top spreading horizontally",
    tags: ["cumulonimbus", "anvil", "thunderstorm", "massive", "incus"],
    category: "clouds",
    cloudType: "cumulonimbus-incus",
    algorithm: "discrete",
    coverage: 0.7,
    altitude: 0.03,
    scale: 2.5,
    cloudCount: 1,
    edgeComplexity: 0.9,
    turbulence: 0.75,
    cloudColor: "#A0A8B8",
    shadowColor: "#384050",
    highlightColor: "#D0D8E0",
    opacity: 0.95,
    sunAngle: 155,
    sunElevation: 0.35,
  },
  {
    id: "lenticular-lens",
    name: "Lenticular Lens",
    description: "Smooth lens-shaped cloud formed by standing mountain waves, UFO-like",
    tags: ["lenticular", "lens", "mountain", "smooth", "wave"],
    category: "clouds",
    cloudType: "lenticular",
    algorithm: "discrete",
    coverage: 0.2,
    altitude: 0.1,
    scale: 1.2,
    cloudCount: 2,
    edgeComplexity: 0.15,
    turbulence: 0.1,
    cloudColor: "#E8ECF4",
    shadowColor: "#A0A8BC",
    highlightColor: "#F8FAFF",
    opacity: 0.8,
    sunAngle: 130,
    sunElevation: 0.6,
  },
  {
    id: "mammatus-pouches",
    name: "Mammatus Pouches",
    description: "Inverted bulging pouch-like formations hanging below a cloud base",
    tags: ["mammatus", "pouches", "dramatic", "inverted"],
    category: "clouds",
    cloudType: "mammatus",
    algorithm: "threshold",
    coverage: 0.6,
    altitude: 0.15,
    scale: 0.8,
    cloudCount: 1,
    edgeComplexity: 0.5,
    turbulence: 0.4,
    cloudColor: "#C8D0D8",
    shadowColor: "#707888",
    highlightColor: "#E0E4EC",
    opacity: 0.85,
    sunAngle: 160,
    sunElevation: 0.35,
  },
  {
    id: "fog-bank-low",
    name: "Fog Bank Low",
    description: "Dense low-lying fog bank with sharp top edge, viewed from above",
    tags: ["fog-bank", "low", "dense", "sharp"],
    category: "clouds",
    cloudType: "fog-bank",
    algorithm: "threshold",
    coverage: 0.7,
    altitude: 0.35,
    scale: 1.0,
    cloudCount: 1,
    edgeComplexity: 0.3,
    turbulence: 0.2,
    cloudColor: "#D8DCE4",
    shadowColor: "#B0B8C4",
    highlightColor: "#E8ECF0",
    opacity: 0.8,
    sunAngle: 135,
    sunElevation: 0.5,
  },
  {
    id: "contrail-thin",
    name: "Contrail Thin",
    description: "Thin straight aircraft contrail slowly spreading in upper atmosphere",
    tags: ["contrail", "thin", "straight", "aircraft"],
    category: "clouds",
    cloudType: "contrail",
    algorithm: "streak",
    coverage: 0.1,
    altitude: 0.05,
    scale: 1.5,
    cloudCount: 2,
    edgeComplexity: 0.1,
    turbulence: 0.05,
    cloudColor: "#F0F4FF",
    shadowColor: "#D8E0EC",
    highlightColor: "#FFFFFF",
    opacity: 0.35,
    sunAngle: 135,
    sunElevation: 0.7,
  },
  {
    id: "pyrocumulus-dark",
    name: "Pyrocumulus Dark",
    description: "Fire-generated cumulus with dark smoky base and explosive cauliflower top",
    tags: ["pyrocumulus", "fire", "dark", "smoke", "cauliflower"],
    category: "clouds",
    cloudType: "pyrocumulus",
    algorithm: "discrete",
    coverage: 0.5,
    altitude: 0.08,
    scale: 1.8,
    cloudCount: 2,
    edgeComplexity: 0.9,
    turbulence: 0.8,
    cloudColor: "#8088A0",
    shadowColor: "#303840",
    highlightColor: "#B0B8C8",
    opacity: 0.9,
    sunAngle: 145,
    sunElevation: 0.4,
  },
  {
    id: "banner-peak",
    name: "Banner Peak",
    description: "Elongated cloud trailing from a mountain peak like a flag",
    tags: ["banner", "mountain", "peak", "elongated"],
    category: "clouds",
    cloudType: "banner-cloud",
    algorithm: "discrete",
    coverage: 0.25,
    altitude: 0.12,
    scale: 1.0,
    cloudCount: 3,
    edgeComplexity: 0.5,
    turbulence: 0.35,
    cloudColor: "#E0E4EC",
    shadowColor: "#98A0B0",
    highlightColor: "#F0F4F8",
    opacity: 0.7,
    sunAngle: 130,
    sunElevation: 0.55,
  },
  {
    id: "pileus-cap",
    name: "Pileus Cap",
    description: "Thin smooth cap cloud draped over the top of a growing cumulus",
    tags: ["pileus", "cap", "thin", "smooth"],
    category: "clouds",
    cloudType: "pileus",
    algorithm: "streak",
    coverage: 0.15,
    altitude: 0.08,
    scale: 1.0,
    cloudCount: 3,
    edgeComplexity: 0.2,
    turbulence: 0.1,
    cloudColor: "#F0F4FF",
    shadowColor: "#D0D8E8",
    highlightColor: "#FFFFFF",
    opacity: 0.3,
    sunAngle: 135,
    sunElevation: 0.65,
  },
];
