import type { CloudPreset } from "./types.js";

export const CLOUD_PRESETS: CloudPreset[] = [
  {
    id: "fair-weather-cumulus",
    name: "Fair Weather Cumulus",
    description: "Scattered puffy cumulus clouds on a clear day, flat bases and rounded tops",
    tags: ["cumulus", "fair", "puffy", "scattered"],
    category: "clouds",
    cloudType: "cumulus",
    algorithm: "discrete",
    coverage: 0.3,
    altitude: 0.15,
    scale: 1.0,
    cloudCount: 5,
    edgeComplexity: 0.6,
    turbulence: 0.3,
    cloudColor: "#FFFFFF",
    shadowColor: "#B0B8C8",
    highlightColor: "#FFFFFF",
    opacity: 0.9,
    sunAngle: 135,
    sunElevation: 0.6,
  },
  {
    id: "towering-cumulus",
    name: "Towering Cumulus",
    description: "Large vertical cumulus with dramatic light and shadow",
    tags: ["cumulus", "towering", "dramatic", "large"],
    category: "clouds",
    cloudType: "cumulus",
    algorithm: "discrete",
    coverage: 0.4,
    altitude: 0.1,
    scale: 1.5,
    cloudCount: 3,
    edgeComplexity: 0.8,
    turbulence: 0.5,
    cloudColor: "#F8F8FF",
    shadowColor: "#8090A8",
    highlightColor: "#FFFFFF",
    opacity: 0.95,
    sunAngle: 150,
    sunElevation: 0.5,
  },
  {
    id: "overcast-stratus",
    name: "Overcast Stratus",
    description: "Flat uniform cloud layer covering most of the sky",
    tags: ["stratus", "overcast", "flat", "gray"],
    category: "clouds",
    cloudType: "stratus",
    algorithm: "threshold",
    coverage: 0.85,
    altitude: 0.2,
    scale: 1.0,
    cloudCount: 1,
    edgeComplexity: 0.2,
    turbulence: 0.15,
    cloudColor: "#D0D4DC",
    shadowColor: "#A8B0BC",
    highlightColor: "#E0E4EC",
    opacity: 0.85,
    sunAngle: 135,
    sunElevation: 0.4,
  },
  {
    id: "stratocumulus-field",
    name: "Stratocumulus Field",
    description: "Regular field of rounded cloud patches with gaps",
    tags: ["stratocumulus", "field", "regular", "patchy"],
    category: "clouds",
    cloudType: "stratocumulus",
    algorithm: "threshold",
    coverage: 0.6,
    altitude: 0.18,
    scale: 0.8,
    cloudCount: 1,
    edgeComplexity: 0.5,
    turbulence: 0.35,
    cloudColor: "#E8ECF0",
    shadowColor: "#A0A8B8",
    highlightColor: "#F8F8FF",
    opacity: 0.9,
    sunAngle: 120,
    sunElevation: 0.55,
  },
  {
    id: "wispy-cirrus",
    name: "Wispy Cirrus",
    description: "High-altitude ice crystal streaks, thin and translucent",
    tags: ["cirrus", "wispy", "high", "thin"],
    category: "clouds",
    cloudType: "cirrus",
    algorithm: "streak",
    coverage: 0.2,
    altitude: 0.05,
    scale: 1.2,
    cloudCount: 8,
    edgeComplexity: 0.3,
    turbulence: 0.2,
    cloudColor: "#F0F4FF",
    shadowColor: "#D0D8E8",
    highlightColor: "#FFFFFF",
    opacity: 0.4,
    sunAngle: 135,
    sunElevation: 0.7,
  },
  {
    id: "sunset-cumulus",
    name: "Sunset Cumulus",
    description: "Cumulus clouds lit from below by warm sunset light",
    tags: ["sunset", "warm", "golden", "dramatic"],
    category: "clouds",
    cloudType: "cumulus",
    algorithm: "discrete",
    coverage: 0.35,
    altitude: 0.12,
    scale: 1.0,
    cloudCount: 4,
    edgeComplexity: 0.7,
    turbulence: 0.4,
    cloudColor: "#F8E8D8",
    shadowColor: "#7868A0",
    highlightColor: "#FFD8A0",
    opacity: 0.9,
    sunAngle: 180,
    sunElevation: 0.15,
  },
  {
    id: "storm-clouds",
    name: "Storm Clouds",
    description: "Dark heavy cumulonimbus with dramatic light contrast",
    tags: ["storm", "dark", "dramatic", "cumulonimbus"],
    category: "clouds",
    cloudType: "cumulonimbus",
    algorithm: "discrete",
    coverage: 0.7,
    altitude: 0.05,
    scale: 2.0,
    cloudCount: 2,
    edgeComplexity: 0.9,
    turbulence: 0.7,
    cloudColor: "#90A0B0",
    shadowColor: "#404858",
    highlightColor: "#C8D0DC",
    opacity: 0.95,
    sunAngle: 160,
    sunElevation: 0.3,
  },
];
