import type { FogPreset } from "./types.js";

export const FOG_PRESETS: FogPreset[] = [
  {
    id: "morning-valley-fog",
    name: "Morning Valley Fog",
    description: "Calm radiation fog settling in valleys at dawn, soft edges",
    tags: ["morning", "valley", "calm", "dawn"],
    category: "fog",
    fogType: "radiation",
    density: 0.6,
    color: "#E8E8F0",
    colorBottom: "#D8D8E8",
    opacity: 0.45,
    fogTop: 0.4,
    fogBottom: 0.85,
    edgeSoftness: 0.35,
    noiseScale: 2.5,
    noiseOctaves: 3,
    patchiness: 0.3,
    warpStrength: 0.2,
  },
  {
    id: "sea-fog",
    name: "Sea Fog",
    description: "Dense advection fog rolling in from the coast, heavy and uniform",
    tags: ["sea", "coast", "dense", "advection"],
    category: "fog",
    fogType: "advection",
    density: 0.8,
    color: "#D0D4DC",
    colorBottom: "#C0C8D4",
    opacity: 0.6,
    fogTop: 0.35,
    fogBottom: 0.95,
    edgeSoftness: 0.2,
    noiseScale: 1.8,
    noiseOctaves: 2,
    patchiness: 0.15,
    warpStrength: 0.3,
  },
  {
    id: "mountain-fog",
    name: "Mountain Fog",
    description: "Upslope fog clinging to mountain ridges, patchy and layered",
    tags: ["mountain", "upslope", "patchy", "ridge"],
    category: "fog",
    fogType: "upslope",
    density: 0.5,
    color: "#E0E4EC",
    colorBottom: "#D0D8E4",
    opacity: 0.4,
    fogTop: 0.3,
    fogBottom: 0.75,
    edgeSoftness: 0.4,
    noiseScale: 3.0,
    noiseOctaves: 4,
    patchiness: 0.5,
    warpStrength: 0.35,
  },
  {
    id: "dense-fog",
    name: "Dense Fog",
    description: "Thick valley fog reducing visibility to near zero",
    tags: ["dense", "thick", "low-visibility"],
    category: "fog",
    fogType: "valley",
    density: 0.9,
    color: "#D8D8E0",
    colorBottom: "#C8C8D8",
    opacity: 0.75,
    fogTop: 0.2,
    fogBottom: 0.95,
    edgeSoftness: 0.15,
    noiseScale: 1.5,
    noiseOctaves: 2,
    patchiness: 0.1,
    warpStrength: 0.15,
  },
  {
    id: "patchy-fog",
    name: "Patchy Fog",
    description: "Scattered fog patches with terrain features visible between gaps",
    tags: ["patchy", "scattered", "light"],
    category: "fog",
    fogType: "radiation",
    density: 0.35,
    color: "#E8ECF4",
    colorBottom: "#E0E4EC",
    opacity: 0.3,
    fogTop: 0.45,
    fogBottom: 0.8,
    edgeSoftness: 0.45,
    noiseScale: 4.0,
    noiseOctaves: 4,
    patchiness: 0.7,
    warpStrength: 0.4,
  },
];
