import type { HazePreset } from "./types.js";

export const HAZE_PRESETS: HazePreset[] = [
  {
    id: "light-haze",
    name: "Light Haze",
    description: "Subtle atmospheric haze softening distant elements",
    tags: ["light", "subtle", "atmospheric", "distance"],
    category: "haze",
    color: "#D8E0EC",
    opacity: 0.25,
    yPosition: 0.3,
    height: 0.5,
    gradientDirection: "bottom-up",
    noiseAmount: 0.2,
    depthSlot: 0.4,
  },
  {
    id: "golden-haze",
    name: "Golden Haze",
    description: "Warm golden atmospheric haze typical of golden hour lighting",
    tags: ["golden", "warm", "golden-hour", "sunset"],
    category: "haze",
    color: "#E8D8C0",
    opacity: 0.3,
    yPosition: 0.25,
    height: 0.55,
    gradientDirection: "bottom-up",
    noiseAmount: 0.25,
    depthSlot: 0.4,
  },
  {
    id: "cool-mist-haze",
    name: "Cool Mist Haze",
    description: "Cool blue-gray atmospheric haze for mountain depth",
    tags: ["cool", "blue", "mountain", "depth"],
    category: "haze",
    color: "#C0C8D8",
    opacity: 0.35,
    yPosition: 0.3,
    height: 0.5,
    gradientDirection: "bottom-up",
    noiseAmount: 0.3,
    depthSlot: 0.5,
  },
  {
    id: "heat-haze",
    name: "Heat Haze",
    description: "Shimmering heat haze rising from ground level",
    tags: ["heat", "shimmer", "hot", "ground"],
    category: "haze",
    color: "#E0D8D0",
    opacity: 0.2,
    yPosition: 0.6,
    height: 0.35,
    gradientDirection: "top-down",
    noiseAmount: 0.5,
    depthSlot: 0.3,
  },
  {
    id: "ink-wash-haze",
    name: "Ink Wash Haze",
    description: "Soft monochrome haze evoking Chinese ink wash painting depth",
    tags: ["ink", "wash", "monochrome", "artistic"],
    category: "haze",
    color: "#C8C8D0",
    opacity: 0.4,
    yPosition: 0.2,
    height: 0.6,
    gradientDirection: "bottom-up",
    noiseAmount: 0.15,
    depthSlot: 0.5,
  },
  {
    id: "twilight-haze",
    name: "Twilight Haze",
    description: "Deep blue-purple atmospheric haze of late twilight",
    tags: ["twilight", "blue", "purple", "evening"],
    category: "haze",
    color: "#9898B8",
    opacity: 0.35,
    yPosition: 0.2,
    height: 0.6,
    gradientDirection: "bottom-up",
    noiseAmount: 0.2,
    depthSlot: 0.45,
  },
];
