import type { MistPreset } from "./types.js";

export const MIST_PRESETS: MistPreset[] = [
  {
    id: "morning-mist",
    name: "Morning Mist",
    description: "Light haze bands creating gentle depth separation at dawn",
    tags: ["morning", "light", "dawn", "gentle"],
    category: "mist",
    density: 0.4,
    color: "#E8E8F0",
    opacity: 0.35,
    bandTop: 0.5,
    bandBottom: 0.8,
    edgeSoftness: 0.3,
    noiseScale: 3.0,
    noiseOctaves: 3,
    layerCount: 3,
    depthSpread: 0.2,
    driftX: 0.1,
    driftPhase: 0,
  },
  {
    id: "mountain-haze",
    name: "Mountain Haze",
    description: "Layered blue-gray haze between mountain ridges, strong depth effect",
    tags: ["mountain", "blue", "layered", "depth"],
    category: "mist",
    density: 0.5,
    color: "#C8D0E0",
    opacity: 0.4,
    bandTop: 0.35,
    bandBottom: 0.85,
    edgeSoftness: 0.25,
    noiseScale: 2.5,
    noiseOctaves: 3,
    layerCount: 4,
    depthSpread: 0.3,
    driftX: 0.05,
    driftPhase: 0.5,
  },
  {
    id: "thick-mist",
    name: "Thick Mist",
    description: "Heavy mist reducing visibility, strong atmospheric presence",
    tags: ["thick", "heavy", "atmospheric", "dense"],
    category: "mist",
    density: 0.7,
    color: "#D8D8E4",
    opacity: 0.55,
    bandTop: 0.3,
    bandBottom: 0.9,
    edgeSoftness: 0.2,
    noiseScale: 2.0,
    noiseOctaves: 3,
    layerCount: 5,
    depthSpread: 0.15,
    driftX: 0.08,
    driftPhase: 0.3,
  },
  {
    id: "layered-mist",
    name: "Layered Mist",
    description: "Multiple distinct mist bands with strong parallax depth",
    tags: ["layered", "parallax", "depth", "multiple"],
    category: "mist",
    density: 0.45,
    color: "#E0E4EC",
    opacity: 0.3,
    bandTop: 0.4,
    bandBottom: 0.85,
    edgeSoftness: 0.35,
    noiseScale: 3.5,
    noiseOctaves: 4,
    layerCount: 6,
    depthSpread: 0.35,
    driftX: 0.12,
    driftPhase: 1.0,
  },
];
